### ISSUE TITLE
Criar evento no meetup.com

### ISSUE THREAD

**Issue by nandomoreirame** [phppr/phpday-2017#1]

**Comment by nandomoreirame** [comment]
Já existe o Grupo PHP PR no meetup.com >> https://www.meetup.com/pt-BR/PHP-PR

**Comment by nandomoreirame** [comment]
@andrebian tem os acessos? pode transferir para que possamos criar o PHP Day lá?

**Comment by andrebian** [comment]
@nandomoreirame passa seu email que eu lhe adiciono.

**Comment by nandomoreirame** [comment]
Acho que já estou lá @andrebian ... o email é: nandomoreira.me@gmail.com

**Comment by yurivecchi** [comment]
Meio fora do escopo, mas podemos atualizar o header com o endereço novo lá no meetup?

**Comment by nandomoreirame** [comment]
sim, e vamos @yurivecchi  :smile:
