### ISSUE TITLE
Enviar apresentação para Fagundez (possível patrocinador)

### ISSUE THREAD

**Issue by cleversonferreira** [phppr/phpday-2017#14]
Após contato com a Carla do marketing da Fagundez (www.fagundez.com) ela demonstrou muito interesse em patrocinar o evento. Fiquei de enviar a apresentação para ela.

(41) 3012-4500
marketing@fagundez.com - Carla

**Comment by cleversonferreira** [comment]
Apresentação enviada, aguardando retorno.

**Comment by nandomoreirame** [comment]
👍
