### ISSUE TITLE
Contato com a StickersDevs

### ISSUE THREAD

**Issue by nandomoreirame** [phppr/phpday-2017#15]
Entrei em contato com o Lauro da [StickersDevs](https://www.stickersdevs.com.br/) para uma possível parceria.

Aguardando o retorno.

**Comment by flaviosilveira** [comment]
@nandomoreirame evoluímos aqui, certo?

**Comment by nandomoreirame** [comment]
SIm, o Lauro respondeu positivamente, está aguardando o meu retorno com a arte para confecção dos adesivos :smiley:
