### ISSUE TITLE
GitKraken MeetUp Package

### ISSUE THREAD

**Issue by yurivecchi** [phppr/phpday-2017#17]
[https://blog.axosoft.com/2017/02/20/gitkraken-meetup-package/](https://blog.axosoft.com/2017/02/20/gitkraken-meetup-package/)

O que vocês acham de entrarmos em contato com eles?

@flaviosilveira @nandomoreirame

**Comment by flaviosilveira** [comment]
@yurivecchi faz a ponta com eles?

**Comment by nandomoreirame** [comment]
Sensacional a ideia @yurivecchi :+1:

**Comment by yurivecchi** [comment]
Como respondo essas?

Contact Email 
- ?
Event Name 
- PHP Day Curitiba

Event Type 
- Meeting

Event URL
- coloco do meetup ou do site?

Expected # of Attendees
- ?

Please include any other information about your event here
- ?

**Comment by flaviosilveira** [comment]
Email flavioaugustosilveira at gmail

Attendees é 45. + 15 staff. Isso que estou calculando.

Não temos URL do evento ainda :-| Estamos discutindo se fazemos um hotsite ou se vai nos symplas da vida mesmo.

Tem a apresentação do evento em inglês como informação adicional.
https://drive.google.com/open?id=0B2CgsELjY872d0VQSzlWVGozTWc

**Comment by yurivecchi** [comment]
Contato já feito, podemos encerrar @flaviosilveira ?

**Comment by flaviosilveira** [comment]
Certo que sim.
Valeu!
