### ISSUE TITLE
Fazer contato com a Zend

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#19]
Solicitar cupons de desconto ou voucher para prova de certificação.

**Comment by nandomoreirame** [comment]
:+1:

**Comment by flaviosilveira** [comment]
Feito um contato via twitter. Aguardando.

**Comment by flaviosilveira** [comment]
Fiz a apresentação em inglês https://drive.google.com/open?id=0B2CgsELjY872d0VQSzlWVGozTWc, passei email para o Cal Evans

Ele me respondeu e estou com o código em mãos para sortearmos.
