### ISSUE TITLE
Levantar orçamentos de Camisetas

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#2]

**Comment by cleversonferreira** [comment]
Falei com a Jéssica a respeito do orçamento, ela falou que para passar um valor mais próximo ela precisa saber algumas coisas:

- Qual vai ser o tipo do tecido? (poliester ou algodão)?
- Onde terão estampas (frente, costas, mangas), e quais serão as respectivas cores?
- Qual vai ser a quantidade ?

Também temos que definir os tamanhos, vamos perguntar na hora da inscrição? ou vamos deixar G e GG como padrão ?

**Comment by cleversonferreira** [comment]
O que acham desse modelo de estampas, as mangas é para caso tenhamos algum patrocinador da camiseta, mas vou pedir dois orçamentos (com e sem estampas nas mangas).

![camiseta-phppr-frente](https://cloud.githubusercontent.com/assets/11292686/23123873/f9a0edcc-f748-11e6-8a35-a94bf5f21df7.JPG)
![camiseta-phppr-costas](https://cloud.githubusercontent.com/assets/11292686/23123872/f99fb04c-f748-11e6-9152-e5868ca4bcb2.JPG)

**Comment by cleversonferreira** [comment]
Pessoal, recebi o orçamento do Bruno, namorado da Jéssica, segue:

> Por ser camiseta colorida, e tom escuro não fica tão mais em conta que em tecido branco. Mas ficaram bom os valores, e espero que fechamos esta parceria.
> 
> Frente/Costa - R$29,90
> Frente/Costa/Manga - R$34,90
> 
> E podemos montar um layout pra você ver a prévia de como irá ficar, só precisaria das artes que vão na camiseta :D 
> Obrigado por enquanto, e fico à disposição! Abraço!

Eu e o @nandomoreirame tinhamos chegado a uma camiseta nesse estilo, o que acha @flaviosilveira ?

![image1](https://cloud.githubusercontent.com/assets/11292686/23239989/5efd7ca6-f949-11e6-8ec1-68d1e99a4ef3.JPG)
![image2](https://cloud.githubusercontent.com/assets/11292686/23239990/5f6ccef8-f949-11e6-87ba-224b71c3460c.JPG)

**Comment by flaviosilveira** [comment]
Legal! Esse preço temos que multiplicar e colocar na apresentação para os apoios e patrocínios.

Da camiseta, particularmente eu colocaria apenas o elefante na frente e esse phppr.org na parte de baixo eu colocaria atrás. Fica um pouco de mistério para quem vê de frente.. ahaha ;)

O que acham? Faria sem a manga daí para reduzir um pouco o custo.

**Comment by nandomoreirame** [comment]
mas vamos fazer a camiseta do evento ou da org?

**Comment by cleversonferreira** [comment]
Acho bacana cara.
qual o número de camisetas que vamos fechar o orçamento? 60 ?


________________________________
De: Flávio Augusto da Silveira <notifications@github.com>
Enviado: sexta-feira, 24 de fevereiro de 2017 16:41
Para: phppr/phpday-2017
Cc: Cleverson Ferreira; Assign
Assunto: Re: [phppr/phpday-2017] Levantar orçamentos de Camisetas (#2)


Legal! Esse preço temos que multiplicar e colocar na apresentação para os apoios e patrocínios.

Da camiseta, particularmente eu colocaria apenas o elefante na frente e esse phppr.org na parte de baixo eu colocaria atrás. Fica um pouco de mistério para quem vê de frente.. ahaha ;)

O que acham? Faria sem a manga daí para reduzir um pouco o custo.

**Comment by flaviosilveira** [comment]
Camiseta do evento né?
60 camisetas fecha a conta.
@cleversonferreira adiciona o valor lá na planilha de controle?

**Comment by nandomoreirame** [comment]
@cleversonferreira e @flaviosilveira nós vamos fazer a camiseta do PHPDay ou do PHPPR?
Pra saber qual logo mandar pra ela. Se for do PHPPR eu mando só a logo da Org, se for do PHPday eu preciso mandar as duas.

**Comment by cleversonferreira** [comment]
@nandomoreirame na minha opinião do PHPDay.

**Comment by flaviosilveira** [comment]
Estou tentando levantar outros orçamentos para confrontarmos e termos algumas outras opiniões.
O orçamento que temos até agora é de 35 cada camiseta em um tecido excelente.

**Comment by nandomoreirame** [comment]
👍

**Comment by nandomoreirame** [comment]
**Esboço do Modelo Azul sem patrocinadores**
![t-shirt phpday-blue2](https://cloud.githubusercontent.com/assets/1318271/24591993/7c8eef52-17e4-11e7-8d40-0641f40b5e9c.png)

**Esboço do Modelo Azul compatrocinadores**
![t-shirt phpday-blue](https://cloud.githubusercontent.com/assets/1318271/24591983/57c030e6-17e4-11e7-8179-12ad30286f4f.png)

**Comment by flaviosilveira** [comment]
Fechado com a Umbler as camisetas.
Precisamos enviar a arte até 02 de Maio.
