### ISSUE TITLE
Escolha da ferramenta para ingressos

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#23]
Precisamos escolher ferramenta para fazer a venda dos ingressos, analisar as taxas e etc.

Primeiras sugestões
https://pt-br.eventials.com/
https://www.sympla.com.br/

**Comment by nandomoreirame** [comment]
:+1:

**Comment by flaviosilveira** [comment]
@nandomoreirame Qual era aquela que você tem contato?

**Comment by nandomoreirame** [comment]
https://www.eventick.com.br/

**Comment by nandomoreirame** [comment]
A que eu tenho o contato é a https://www.sympla.com.br/
Na verdade o cara me mandou um email para migrar do Eventick para eles...

**Comment by flaviosilveira** [comment]
Vamos fazer lá então.
