### ISSUE TITLE
Definição do Kit para os inscritos

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#25]
Sugestão até agora
Xícara / Camiseta / Credencial / Caneta / Bloco / Adesivo PHPPR

**Comment by nandomoreirame** [comment]
:+1:

**Comment by nandomoreirame** [comment]
-> #26

**Comment by flaviosilveira** [comment]
Esse é o KIT ideal. Caso a gente não consiga fechar os patrocinadores necessário revisamos.
