### ISSUE TITLE
Criação Hotsite

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#27]
Apenas a plataforma do Sympla não será possível para inserir a logos dos apoiadores e patrocinadores. Precisamos de uma página dentro do site do PHPPR.

Acredito que no wordpress mesmo já resolve.

**Comment by nandomoreirame** [comment]
Podemos usar o **[Conf Boilerplate](https://github.com/braziljs/conf-boilerplate)**, já tem uma estrutura de conferência com espaço para os palestrantes, palestras e patrocinadores.
- Demo: http://braziljs.github.io/conf-boilerplate/
- Repositório: https://github.com/braziljs/conf-boilerplate

**Comment by nandomoreirame** [comment]
@flaviosilveira está em andamento essa atividade? posso começar faço rapidão usando o Conf Boilerplate?
