### ISSUE TITLE
Levantar orçamentos de credenciais

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#3]

**Comment by cleversonferreira** [comment]
Para esse orçamento a Jéssica precisa do tamanho das credenciais, conversei com o @nandomoreirame e achamos bacana algo próximo de 10X15. O que acha @flaviosilveira.
Em relação a arte, ela disse que é livre.

**Comment by flaviosilveira** [comment]
O tamanho está ótimo. Vamos orçar com ela.

**Comment by flaviosilveira** [comment]
@cleversonferreira Conseguiram fechar um valor das credenciais com a Jéssica?

**Comment by cleversonferreira** [comment]
Então @flaviosilveira só para registrar nossa conversa com a Jess, ela passou que ficaria no máximo R$1,50, com cordão personalizado com a nossa logo.

**Comment by flaviosilveira** [comment]
Estou tentando levantar outros orçamentos para confrontarmos e termos algumas outras opiniões.

**Comment by nandomoreirame** [comment]
👍
