### ISSUE TITLE
Levantar Orçamentos de Adesivos

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#4]

**Comment by cleversonferreira** [comment]
Falei com a Jéssica e ela pediu o formato dos adesivos, cada tipo de formato tem uma variação de preço (quadrado, redondo, recortado). E discutindo isso com o @nandomoreirame achamos bacana o formato recortado, o que você acha @flaviosilveira

**Comment by flaviosilveira** [comment]
@nandomoreirame @cleversonferreira 
Os adesivos não fechamos com o pessoal da Stickers?

**Comment by nandomoreirame** [comment]
Sim. @flaviosilveira @cleversonferreira 
A [StickersDevs](https://www.stickersdevs.com.br/) irá patrocinar o adesivo oficial [personalizado do **PHPDay**](https://www.stickersdevs.com.br/stickers-personalizados/) e além disso irei levantar orçamento para mais adesivos diversos. Aguardem meu retorno.

**Comment by nandomoreirame** [comment]
Issue #15
