### ISSUE TITLE
Criar apresentação para possíveis patrocinadores

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#5]
- Local
- Horário
- Quantidade palestras
- Mostrar orçamentos e propor que as empresas apoiem com o dinheiro de um dos orçamentos

**Comment by flaviosilveira** [comment]
@cleversonferreira Consegue colocar o que você fez naquela apresentação que deixamos no Drive?

**Comment by cleversonferreira** [comment]
@flaviosilveira conforme conversamos, compartilhei via Keynote.
A ultima versão você disponibilizou em algum lugar ?

**Comment by flaviosilveira** [comment]
PDF enviado para organização.
Aguardando ideia do grupo.

Apresentação já foi enviada para alguns possíveis patrocinadores.

**Comment by nandomoreirame** [comment]
👍

**Comment by flaviosilveira** [comment]
Inglês e português.
Peçam o link se precisar.
