### ISSUE TITLE
Fazer contato com casa do código

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#6]
Conversar para ver o que eles podem mandar para sortearmos no evento

**Comment by andrebian** [comment]
Posso ajudar nisso.

**Comment by nandomoreirame** [comment]
Show @andrebian :metal:

**Comment by flaviosilveira** [comment]
Enviei um tweet para eles. Aguardando.

**Comment by cleversonferreira** [comment]
@andrebian @flaviosilveira 
Alguma atualização nesse tópico em relação a resposta do pessoal da casa do código?

**Comment by flaviosilveira** [comment]
Tivemos resposta.
Enviado proposta por email para eles.
Aguardando resposta.

**Comment by nandomoreirame** [comment]
👍

**Comment by flaviosilveira** [comment]
Fechado!
Teremos 2 EBooks para sorteio e cupom de desconto para todos os participantes.

Precisamos adicionar a logo e o nome deles definitivo ao projeto.

**Comment by flaviosilveira** [comment]
Artes
https://www.dropbox.com/s/f3rgc1ai98vmo2l/logo%20-%20novo%20slogan.zip?dl=0

**Comment by flaviosilveira** [comment]
Confirmar se a Caelum vai sobrescrever o apoio da Casa do código

**Comment by flaviosilveira** [comment]
Fechado com a Caelum.
3 ebooks, 1 mês de alura, cupons de desconto para todos e brindes.
