### ISSUE TITLE
Fazer contato com a Novatec

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#7]
Conversar para ver o que eles podem mandar para sortearmos no evento

**Comment by flaviosilveira** [comment]
Enviado um tweet para eles. Aguardando.

**Comment by flaviosilveira** [comment]
Tivemos resposta.
Enviado proposta por email para eles.
Aguardando resposta.

**Comment by nandomoreirame** [comment]
👍

**Comment by flaviosilveira** [comment]
Sem resposta até hoje.

**Comment by flaviosilveira** [comment]
Vão patrocinar as canetas e apoiar com um livro para sorteio.
Fechado!
