### ISSUE TITLE
Pagar Limpeza do auditório da Aldeia

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#8]
R$80

**Comment by straube** [comment]
@flaviosilveira Vi que isso não está nas cotas de patrocínio, mas eu posso pagar pela minha empresa.

**Comment by flaviosilveira** [comment]
@straube Que tal apoiar com a refeição para os palestrantes (R$ 150)?
Tem outras coisas com valor pequeno Canetas, Credenciais. O que acha?
https://drive.google.com/open?id=0B2CgsELjY872RVFzdGJBclNVeVE

**Comment by straube** [comment]
@flaviosilveira Posso apoiar com a refeição para os paletrantes, sim. Como fazemos?

**Comment by flaviosilveira** [comment]
@straube Vamos falar.

**Comment by flaviosilveira** [comment]
@straube Me manda um Hi no WhatsApp
