### ISSUE TITLE
Precisamos de uma pessoa para a recepção

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/phpday-2017#9]
No dia do evento, precisamos alguém na recepção para direcionar as pessoas para o auditório.

**Comment by yurivecchi** [comment]
Se for apenas para redirecionar não seria melhor deixar um cartaz/banner e deixar a pessoa ajudando no credenciamento?

**Comment by flaviosilveira** [comment]
é uma certa exigência do pessoal da Aldeia @yurivecchi .
podemos tentar conversar com eles, mas caso comecem a perguntar lá na frente sobre o PHP Day eles vão querer cobrar da gente.
